apiVersion: v1
kind: Secret
metadata:
  name: jbpm-secret
  namespace: jbpm
  labels:
    app.kubernetes.io/name: jbpm
    app.kubernetes.io/part-of: jbpm-stack
type: Opaque
stringData:
  JBPM_DB_USER: jbpm
  JBPM_DB_PASSWORD: jbpm
